### ISSUE TITLE
edb.materials.load_amat(material_file) loading wrong material

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb#156] opened 2024-02-08 10:37 UTC
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues

### 🐞 Description of the bug

Loading Amat files provides wrong material values in EDB

### ✅ Expected behavior

get correct values

### 📝 Steps to reproduce

NA

### 📃 Relevant log output

NA

**Comment by SMoraisAnsys** [comment] 2024-03-03 04:28
@svandenb-dev Is it related to the discussion we had last friday ? If not, can you show me a reproducer so that I could help you on that ?

**Comment by svandenb-dev** [comment] 2024-03-05 13:50
@SMoraisAnsys this was reported by users. Loaded material values are wrong. To reproduce we just need to load the file and check material properties

**Comment by SMoraisAnsys** [comment] 2024-03-07 17:22
I'm not able to reproduce the problem but there is something that we should rework with the way materials are currently handled. Sometimes their names are handled as they are provided, e.g. `"FR4_epoxy"`, and other times the names are "lowered", e.g. `"fr4_epoxy"`. This is an issue when one is trying to perform multiple actions mixing those concepts, e.g. materials `duplicate`, `_load_materials`.

How would you like to work on this issue ?

**Comment by SMoraisAnsys** [comment] 2024-04-15 14:31
Recent refactoring and features should have handled this issue, see #290 and #361.
Closing issue but feel free to open it back with extra information if recent updates were not sufficient enough.

**Closed by SMoraisAnsys** 2024-04-15 14:31 UTC
Labels: bug
