### ISSUE TITLE
Bug located in pyedb create_bundle_wave_port

### ISSUE THREAD

**Issue by cmesibov** [ansys/pyedb#805] opened 2024-09-19 15:33 UTC
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When running PyEdb code to add a coupled wave port, the function create_bundle_wave_port() fails at terminal.py in do_renormalize().  

### Steps To Reproduce

def TestEDBPortCreation():
    edb = pyaedt.Edb(edbversion="2025.1", edbpath=portsEDB)
    edb_hfss = edb.hfss
    posTraceEndPoint = edb.modeler.paths[2].arcs[2].end
    negTraceEndPoint = edb.modeler.paths[3].arcs[3].end
    posPath = edb.modeler.paths[2]
    negPath = edb.modeler.paths[3]
    posTraceWidth = posPath.width
    posTraceEndPoint = [posTraceEndPoint[0] + posTraceWidth/2, posTraceEndPoint[1]]
    negTraceWidth = negPath.width
    negTraceEndPoint = [negTraceEndPoint[0] - negTraceWidth / 2, negTraceEndPoint[1]]
    posID = posPath.id
    NegID = negPath.id
    results = edb_hfss.create_bundle_wave_port([posID,NegID],[posTraceEndPoint, negTraceEndPoint], 'msPort')
    edb.save_edb()
    edb.close_edb()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

(venv) PS D:\Companies\AMD\scripts\VRM_testing> python -m pip freeze
annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3
attrs==24.2.0
cffi==1.17.1
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.3.0
cycler==0.12.1
defusedxml==0.7.1
exceptiongroup==1.2.2
fonttools==4.53.1
fpdf2==2.7.9
iniconfig==2.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.7
llvmlite==0.43.0
matplotlib==3.9.2
numba==0.60.0
numpy==1.26.4
packaging==24.1
pandas==2.2.2
pillow==10.4.0
pluggy==1.5.0
plumbum==1.8.3
psutil==6.0.0
pyaedt==0.10.2
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyedb==0.28.0
pyedt==0.1.4
pyparsing==3.1.4
pytest==8.3.3
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.2
pywin32==306
PyYAML==6.0.2
referencing==0.35.1
rpds-py==0.20.0
rpyc==6.0.0
Rtree==1.3.0
scikit-rf==1.3.0
scipy==1.14.1
six==1.16.0
toml==0.10.2
tomli==2.0.1
typing_extensions==4.12.2
tzdata==2024.1

**Comment by SMoraisAnsys** [comment] 2024-10-18 07:58
@cmesibov I'm not able to reproduce your bug locally. For example, modifying a bit your code and executing the following code  works with AEDT 24.2 and 25.1. 

```python
from pyedb import Edb


edb = Edb(edbversion="2025.1")

edb.stackup.add_layer("GND", "Gap")
edb.stackup.add_layer("Substrat", "GND", layer_type="dielectric", thickness="0.2mm", material="Duroid (tm)")
edb.stackup.add_layer("TOP", "Substrat")
trace_length = 10e-3
trace_width = 200e-6
trace_gap = 1e-3
edb.modeler.create_trace(
    path_list=[[-trace_gap / 2, 0.0], [-trace_gap / 2, trace_length]],
    layer_name="TOP",
    width=trace_width,
    net_name="signal0",
    start_cap_style="Flat",
    end_cap_style="Flat",
)
edb.modeler.create_trace(
    path_list=[[-trace_gap / 2 + 1, 0.0], [-trace_gap / 2 + 1, trace_length]],
    layer_name="TOP",
    width=trace_width,
    net_name="signal1",
    start_cap_style="Flat",
    end_cap_style="Flat",
)
edb.modeler.create_trace(
    path_list=[[-trace_gap / 2 + 2, 0.0], [-trace_gap / 2 + 2, trace_length]],
    layer_name="TOP",
    width=trace_width,
    net_name="signal2",
    start_cap_style="Flat",
    end_cap_style="Flat",
)
edb.modeler.create_trace(
    path_list=[[-trace_gap / 2 + 3, 0.0], [-trace_gap / 2 + 3, trace_length]],
    layer_name="TOP",
    width=trace_width,
    net_name="signal3",
    start_cap_style="Flat",
    end_cap_style="Flat",
)


posTraceEndPoint = edb.modeler.paths[2].arcs[2].end
negTraceEndPoint = edb.modeler.paths[3].arcs[3].end
posPath = edb.modeler.paths[2]
negPath = edb.modeler.paths[3]
posTraceWidth = posPath.width
posTraceEndPoint = [posTraceEndPoint[0] + posTraceWidth/2, posTraceEndPoint[1]]
negTraceWidth = negPath.width
negTraceEndPoint = [negTraceEndPoint[0] - negTraceWidth / 2, negTraceEndPoint[1]]
posID = posPath.id
NegID = negPath.id
results = edb.hfss.create_bundle_wave_port([posID,NegID],[posTraceEndPoint, negTraceEndPoint], 'msPort')
edb.save_edb()
edb.close_edb()

```

I'm closing this issue for the moment. If you still have a problem feel free to open it again but add enough input to your issue for us to be able to reproduce your bug.

**Closed by SMoraisAnsys** 2024-10-18 07:58 UTC
Labels: bug
